;;; nelisp-alloc-check-test.el --- checked-allocator (Doc 170 Stage 2) tests  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 zawatton

;; This file is not part of GNU Emacs.

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Host-side checks for the standalone checked allocator (Doc 170 §5 /
;; Doc 168 Phase 2b).  The runtime logic lives in AOT-grammar forms
;; generated by scripts/nelisp-standalone-build.el; these tests verify
;; the generated forms' structure and invariants without a standalone
;; rebuild:
;;
;;   * guard-word encoding round trip (generation tag in the low 32
;;     bits, guard magic in the high 32);
;;   * the +16 size padding preserves "checked BT = raw BT + 16" for
;;     every request size (so free-list bucketing / sweep walks are
;;     consistent whichever mode allocated the block);
;;   * `nl_alloc_bytes' is the wrapper and the historical allocator
;;     survives as `nl_alloc_bytes_uncheck' in every target's arena;
;;   * the free path verifies the redzone before poison;
;;   * builtin dispatch / fboundp-surface / bss-slot wiring;
;;   * the Windows boot env probe compares the exact UTF-16LE name.
;;
;; End-to-end runtime behaviour is covered by the Makefile target
;; `standalone-reader-checked' (build + three smoke runs).

;;; Code:

(setq load-prefer-newer t)

(require 'ert)
(require 'cl-lib)

(let* ((this (or load-file-name buffer-file-name))
       (test-dir (and this (file-name-directory this)))
       (repo-root (and test-dir
                       (file-name-directory
                        (directory-file-name test-dir)))))
  (dolist (dir '("lisp" "src" "scripts"))
    (let ((path (and repo-root (expand-file-name dir repo-root))))
      (when (and path (file-directory-p path))
        (add-to-list 'load-path path)))))

(require 'nelisp-standalone-build)

(defun nelisp-alloc-check-test--tree-member-p (needle tree)
  "Return non-nil when NEEDLE occurs as a subtree of TREE."
  (cond
   ((equal needle tree) t)
   ((consp tree)
    (or (nelisp-alloc-check-test--tree-member-p needle (car tree))
        (nelisp-alloc-check-test--tree-member-p needle (cdr tree))))))

(defun nelisp-alloc-check-test--defun (name forms)
  "Return the (defun NAME ...) form in FORMS, or nil."
  (cl-find-if (lambda (f)
                (and (consp f) (eq (car f) 'defun) (eq (cadr f) name)))
              forms))

(defun nelisp-alloc-check-test--calls-p (caller callee forms)
  "Return non-nil when the CALLER defun in FORMS references CALLEE."
  (let ((def (nelisp-alloc-check-test--defun caller forms)))
    (and def (nelisp-alloc-check-test--tree-member-p
              callee (cl-copy-list (cddr def))))))

;;; Guard-word encoding -----------------------------------------------

(ert-deftest nelisp-alloc-check-guard-constants-consistent ()
  "Full guard word = HI << 32, HI positive and below 2^31.
The HI bound keeps the stored guard a positive i64, so the runtime's
`(sar guard 32)' recovers HI exactly (arithmetic shift of a positive)."
  (should (< 0 nelisp-standalone--alloc-check-guard-hi))
  (should (< nelisp-standalone--alloc-check-guard-hi (ash 1 31)))
  (should (= nelisp-standalone--alloc-check-guard-word
             (ash nelisp-standalone--alloc-check-guard-hi 32))))

(ert-deftest nelisp-alloc-check-guard-generation-roundtrip ()
  "Generation tag survives the guard-word pack/unpack used at runtime.
Pack = word + (gen & #xFFFFFFFF) (the stamp), unpack-hi = floor shift
by 32 (`sar' on a positive value), unpack-gen = low 32 bits."
  (dolist (gen (list 1 2 4095 (1- (ash 1 32)) (+ 7 (ash 1 32)) (ash 1 40)))
    (let ((guard (+ nelisp-standalone--alloc-check-guard-word
                    (logand gen #xFFFFFFFF))))
      (should (= (ash guard -32) nelisp-standalone--alloc-check-guard-hi))
      (should (= (logand guard #xFFFFFFFF) (logand gen #xFFFFFFFF))))))

(ert-deftest nelisp-alloc-check-pad-preserves-block-total-shift ()
  "BT(size + 16) = BT(size) + 16 for every request size.
BT models the runtime's `nl_block_total': 8-byte header + payload
rounded up to 8 with an 8-byte minimum.  A constant +16 shift keeps
every checked block exactly one guard + one site word larger than its
unchecked shape, for all sizes including the sub-minimum ones."
  (cl-flet ((bt (size)
              (let ((p (* 8 (ceiling size 8))))
                (+ 8 (max 8 p)))))
    (dotimes (i 5000)
      (let ((size (1+ i)))
        (should (= (bt (+ size 16)) (+ 16 (bt size))))))))

;;; Environment-probe name constants ------------------------------------

(ert-deftest nelisp-alloc-check-env-name-words-roundtrip ()
  "The packed UTF-16LE words decode back to \"NELISP_ALLOC_CHECK\"."
  (pcase-let ((`(,w0 ,w1 ,w2 ,w3 ,w4)
               (nelisp-standalone--alloc-check-env-name-words))
              (name nelisp-standalone--alloc-check-env-name))
    (should (equal name "NELISP_ALLOC_CHECK"))
    (let ((decoded ""))
      (dolist (w (list w0 w1 w2 w3))
        (dotimes (i 4)
          (setq decoded
                (concat decoded
                        (char-to-string (logand (ash w (* -16 i)) #xFFFF))))))
      (dotimes (i 2)
        (setq decoded
              (concat decoded
                      (char-to-string (logand (ash w4 (* -16 i)) #xFFFF)))))
      (should (equal decoded name)))))

;;; Arena source wiring -------------------------------------------------

(ert-deftest nelisp-alloc-check-arena-wrapper-every-target ()
  "Every standalone target's arena defines the wrapper + raw allocator."
  (dolist (target '(linux-x86_64 windows-x86_64 macos-aarch64
                    linux-aarch64 windows-aarch64))
    (let* ((nelisp-standalone--target target)
           (arena (cdr (nelisp-standalone--target-arena-source))))
      (should (nelisp-alloc-check-test--defun 'nl_alloc_bytes arena))
      (should (nelisp-alloc-check-test--defun 'nl_alloc_bytes_uncheck arena))
      (should (nelisp-alloc-check-test--defun 'nl_alloc_check_stamp arena))
      (should (nelisp-alloc-check-test--defun 'nl_alloc_check_verify arena))
      (should (nelisp-alloc-check-test--defun 'nl_alloc_check_env_enable arena))
      ;; The wrapper composes pad -> raw alloc -> stamp.
      (should (nelisp-alloc-check-test--calls-p
               'nl_alloc_bytes 'nl_alloc_bytes_uncheck arena))
      (should (nelisp-alloc-check-test--calls-p
               'nl_alloc_bytes 'nl_alloc_check_stamp arena))
      (should (nelisp-alloc-check-test--calls-p
               'nl_alloc_bytes 'nl_alloc_check_size arena))
      ;; Exactly one defun per name (the rename really removed the
      ;; original `nl_alloc_bytes' definition).
      (should (= 1 (cl-count-if
                    (lambda (f) (and (consp f) (eq (car f) 'defun)
                                     (eq (cadr f) 'nl_alloc_bytes)))
                    arena))))))

(ert-deftest nelisp-alloc-check-stamp-and-verify-share-magic ()
  "The stamp writes the same magic the verifier compares against."
  (let ((forms (nelisp-standalone--alloc-check-arena-forms)))
    ;; Stamp writes GUARD-WORD + (gen & mask).
    (should (nelisp-alloc-check-test--tree-member-p
             `(+ ,nelisp-standalone--alloc-check-guard-word
                 (logand gen 4294967295))
             (nelisp-alloc-check-test--defun 'nl_alloc_check_stamp forms)))
    ;; Verifier compares (sar guard 32) against GUARD-HI.
    (should (nelisp-alloc-check-test--tree-member-p
             nelisp-standalone--alloc-check-guard-hi
             (nelisp-alloc-check-test--defun 'nl_alloc_check_verify forms)))))

(ert-deftest nelisp-alloc-check-free-path-verifies-before-poison ()
  "`nl_gc_free_block_link' calls the redzone verifier, and the verify
call precedes the poison-on-free arm in evaluation order (the verify
is the first `nl_seq2' argument wrapping the historical body)."
  (let* ((def (nelisp-alloc-check-test--defun
               'nl_gc_free_block_link
               (cdr nelisp-standalone--gc-source)))
         (body (car (cl-cdddr def))))
    (should def)
    ;; Outermost form: (nl_seq2 (nl_alloc_check_verify hdr) <rest>).
    (should (eq (car body) 'nl_seq2))
    (should (equal (cadr body) '(nl_alloc_check_verify hdr)))
    ;; Poison still present downstream of the verify.
    (should (nelisp-alloc-check-test--tree-member-p
             'nl_gc_poison_fill (caddr body)))))

;;; Builtin dispatch / surface -------------------------------------------

(ert-deftest nelisp-alloc-check-report-dispatch-entry ()
  "`nelisp--alloc-check-report' has a dispatch arm bound to the census
helper, and stays out of the baked-eval dispatch subset."
  (let ((entry (cl-find-if
                (lambda (e) (equal (car e) '(:lit "nelisp--alloc-check-report")))
                nelisp-standalone--applyfn-dispatch-table)))
    (should entry)
    (should (equal (cdr entry) '(bf_alloc_check_report out)))
    (should-not (cl-find-if
                 (lambda (e)
                   (equal (car e) '(:lit "nelisp--alloc-check-report")))
                 nelisp-standalone--applyfn-dispatch-table-baked))))

(ert-deftest nelisp-alloc-check-report-impl-in-census-helpers ()
  "The report + leak-scan defuns live in the reader-only census unit."
  (let ((forms nelisp-standalone--applyfn-census-helpers))
    (should (nelisp-alloc-check-test--defun 'bf_alloc_check_report forms))
    (should (nelisp-alloc-check-test--defun 'bf_ac_scan_chunk forms))
    (should (nelisp-alloc-check-test--defun 'bf_ac_scan_chunks forms))
    (should (nelisp-alloc-check-test--calls-p
             'bf_alloc_check_report 'bf_ac_scan_chunks forms))
    ;; The leak scan skips boot blocks and free blocks.
    (should (nelisp-alloc-check-test--calls-p
             'bf_ac_scan_chunk 'nl_gc_is_boot forms))))

(ert-deftest nelisp-alloc-check-report-registered-builtin-name ()
  "The report builtin is on the reader fboundp surface list."
  (should (member "nelisp--alloc-check-report"
                  nelisp-standalone--reader-builtins)))

(ert-deftest nelisp-alloc-check-debug-switch-extension ()
  "`bf_debug_switch' chains into `bf_debug_switch_ext' for codes 19+,
and (Doc 180 Phase 2 item 2, 2026-08-23) `bf_debug_switch_ext' itself now
chains into `bf_debug_switch_ext2' for anything it does not handle
(codes 22/23, the new frame-recording-only arm bit, were inserted ahead
of the historical 19/20/21 chain rather than appended after it) --
`bf_debug_switch_ext2' is the historical `bf_debug_switch_ext' body,
renamed, and still handles enable (19) / disable (20) / site id (21)."
  (let ((forms nelisp-standalone--applyfn-core-helpers))
    (should (nelisp-alloc-check-test--defun 'bf_debug_switch_ext forms))
    (should (nelisp-alloc-check-test--defun 'bf_debug_switch_ext2 forms))
    (should (nelisp-alloc-check-test--calls-p
             'bf_debug_switch 'bf_debug_switch_ext forms))
    (should (nelisp-alloc-check-test--calls-p
             'bf_debug_switch_ext 'bf_debug_switch_ext2 forms))
    (let ((ext (nelisp-alloc-check-test--defun 'bf_debug_switch_ext2 forms)))
      (dolist (code '(19 20 21))
        (should (nelisp-alloc-check-test--tree-member-p
                 `(= (wf_argval args 0) ,code) ext)))
      ;; 21 stores ARG1 into the site slot (+24).
      (should (nelisp-alloc-check-test--tree-member-p
               '(ptr-write-u64 (data-addr nl_alloc_check) 24 (wf_argval args 1))
               ext))
      ;; 19 must NOT arm verification (slot +8 stays untouched by 19).
      (should-not (nelisp-alloc-check-test--tree-member-p
                   '(ptr-write-u64 (data-addr nl_alloc_check) 8 1) ext)))))

;;; BSS slot block --------------------------------------------------------

(ert-deftest nelisp-alloc-check-bss-slot-declared ()
  "`nl_alloc_check' is a bss global and the unit reserves its 96 bytes.
The 4194304 below is the root-stack region size (Doc 152 Stage 3 grew it
1 MiB -> 4 MiB); every arena-base bss symbol after the region moves with it,
so this expectation is written against that constant rather than a literal."
  (let* ((unit (nelisp-standalone--arena-base-slot-unit))
         (sections (plist-get unit :sections))
         (bss-size (cdr (assq 'bss sections)))
         (sym (cl-find-if (lambda (s)
                            (equal (plist-get s :name) "nl_alloc_check"))
                          (plist-get unit :symbols))))
    (should sym)
    (should (eq (plist-get sym :section) 'bss))
    (should (= (plist-get sym :value) (+ 57616 4194304)))
    ;; The block's 96 bytes fit inside the unit's bss reservation.
    (should (>= bss-size (+ 57616 4194304 96)))
    ;; No overlap with any other declared bss symbol's start against
    ;; `nl_alloc_check''s own 96-byte span.  Doc 180 Phase 2 item 3
    ;; (2026-08-23) appended `nl_bt_snapshot' right AFTER `nl_alloc_check'
    ;; in this same unit, so "every other symbol comes before" is no
    ;; longer the invariant -- "no other symbol starts inside this span"
    ;; is, and holds for a symbol on either side.
    (dolist (other (plist-get unit :symbols))
      (unless (equal (plist-get other :name) "nl_alloc_check")
        (should (or (< (plist-get other :value) (+ 57616 4194304))
                    (>= (plist-get other :value) (+ 57616 4194304 96))))))))

;;; Windows boot env probe ------------------------------------------------

(ert-deftest nelisp-alloc-check-windows-env-probe-wired ()
  "Windows OS forms define the probe and the environ walk calls it."
  (let* ((nelisp-standalone--target 'windows-x86_64)
         (forms (nelisp-standalone--reader-os-base-forms)))
    (should (nelisp-alloc-check-test--defun 'nl_alloc_check_env_probe forms))
    (should (nelisp-alloc-check-test--calls-p
             'nl_win_environ_walk 'nl_alloc_check_env_probe forms))
    ;; The probe requires an 18-char name, "=1" value, and enables via
    ;; the arena-unit helper (cross-unit call, no data-addr here).
    (let ((probe (nelisp-alloc-check-test--defun
                  'nl_alloc_check_env_probe forms)))
      (should (nelisp-alloc-check-test--tree-member-p
               '(= (- eqpos off) 18) probe))
      (should (nelisp-alloc-check-test--tree-member-p
               '(nl_alloc_check_env_enable) probe))
      (should (nelisp-alloc-check-test--tree-member-p
               '(= (ptr-read-u16 block (* (+ eqpos 1) 2)) 49) probe))
      (pcase-let ((`(,w0 ,_w1 ,_w2 ,_w3 ,w4)
                   (nelisp-standalone--alloc-check-env-name-words)))
        (should (nelisp-alloc-check-test--tree-member-p w0 probe))
        (should (nelisp-alloc-check-test--tree-member-p w4 probe))))))

(ert-deftest nelisp-alloc-check-non-windows-omits-probe ()
  "Targets without runtime env inheritance neither define nor call the
probe (the symbol must not dangle in their environ walk)."
  (dolist (target '(linux-x86_64 macos-aarch64 linux-aarch64))
    (let* ((nelisp-standalone--target target)
           (forms (nelisp-standalone--reader-os-base-forms)))
      (should-not (nelisp-alloc-check-test--tree-member-p
                   'nl_alloc_check_env_probe forms)))))

(provide 'nelisp-alloc-check-test)

;;; nelisp-alloc-check-test.el ends here
