cmake_minimum_required(VERSION 3.16)
project(fcitx5-nelisp-ime VERSION 0.1.0 LANGUAGES CXX)
find_package(Fcitx5Core REQUIRED)
include("${FCITX_INSTALL_CMAKECONFIG_DIR}/Fcitx5Utils/Fcitx5CompilerSettings.cmake")
add_library(nelisp-ime SHARED nelisp-ime.cpp ../../common/nelisp_ime_client.cpp)
target_compile_features(nelisp-ime PRIVATE cxx_std_17)
target_include_directories(nelisp-ime PRIVATE ../../common)
target_link_libraries(nelisp-ime PRIVATE Fcitx5::Core)
set_target_properties(nelisp-ime PROPERTIES PREFIX "")
configure_file(nelisp-ime-addon.conf.in nelisp-ime-addon.conf)
configure_file(nelisp-ime.conf.in nelisp-ime.conf)
install(TARGETS nelisp-ime DESTINATION "${FCITX_INSTALL_LIBDIR}/fcitx5")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/nelisp-ime-addon.conf" RENAME nelisp-ime.conf DESTINATION "${FCITX_INSTALL_PKGDATADIR}/addon")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/nelisp-ime.conf" DESTINATION "${FCITX_INSTALL_PKGDATADIR}/inputmethod")
