;;; nelisp-actor-cps-dump.el --- Build-time CPS transform for nelisp-actor -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Doc 193 §4.3/§4.4 Phase 1: `generator.el' is not vendored for the
;; standalone substrate, so no `(nelisp-actor-lambda ...)' form can be
;; macroexpanded there.  This script is the build-time transform that
;; sidesteps the problem instead of solving it on that substrate: run
;; under a REAL Emacs (where `generator.el' unquestionably works, since
;; it ships with Emacs), macroexpand a named `defun''s
;; `nelisp-actor-lambda' subforms with the real `iter-lambda'/
;; `iter-yield', and write the fully-expanded result -- ordinary
;; closures, no CPS macro calls left anywhere -- as a new, checked-in
;; source file.  The standalone reader is never asked to load or
;; macroexpand `generator.el' at all; it only executes closures real
;; Emacs's own macro-expander already produced, using the tiny runtime
;; shim `nelisp-actor.el' installs when `(featurep 'generator)' is nil
;; (`iter-next'/`iter-close'/`iter-end-of-sequence').
;;
;; Precedent for this pattern in this exact repo: `nl-ns''s host
;; baseline (`packages/nl-ns/baseline/emacs-30.1.el', generated by
;; `packages/nl-ns/scripts/nl-ns-dump-baseline.el' run under a real
;; Emacs, read back by an analyzer that itself runs on `target/nelisp')
;; is the same shape -- a fact host Emacs alone can produce correctly,
;; generated once, consumed by the standalone substrate as data.  This
;; applies the identical pattern to macro-expansion OUTPUT rather than
;; baseline DATA.
;;
;; Run from the repository root, under a REAL Emacs:
;;
;;   emacs -Q --batch -L packages/nelisp-actor/src \
;;     -l packages/nelisp-actor/scripts/nelisp-actor-cps-dump.el \
;;     --eval "(nelisp-actor-cps-dump-write \
;;               \"examples/nelisp-actor/two-actor-exchange.el\" \
;;               'nelisp-demo-ping-pong \
;;               \"packages/nelisp-actor/generated/two-actor-exchange-cps.el\" \
;;               'nelisp-demo-ping-pong-standalone)"
;;
;; or: make nelisp-actor-cps-baseline
;;
;; AI.md rule 7 ("record generated data recipes next to the
;; generator"): the recipe is the `make nelisp-actor-cps-baseline'
;; target in the top-level Makefile, next to this file; do not
;; hand-edit `packages/nelisp-actor/generated/*.el' -- regenerate it.

;;; Code:

(require 'cl-lib)
(require 'generator)
(require 'nelisp-actor)

(unless (featurep 'generator)
  (error "nelisp-actor-cps-dump: real generator.el did not load -- \
refusing to bake a transform whose macro-expansion oracle is unavailable"))

(defun nelisp-actor-cps-dump--struct-accessors (struct-name)
  "Return the accessor function symbols `cl-defstruct' STRUCT-NAME defined.
Reads them back from `cl-struct-slot-info' (skipping the synthetic
`cl-tag-slot') rather than hardcoding the field list, so this stays
correct if `nelisp-actor''s own fields ever change without anyone
having to remember to update this script too."
  (let ((slots (cl-struct-slot-info struct-name))
        (out nil))
    (dolist (slot slots)
      (unless (eq (car slot) 'cl-tag-slot)
        (push (intern (format "%s-%s" struct-name (car slot))) out)))
    (nreverse out)))

(defun nelisp-actor-cps-dump--call-without-struct-inlining (thunk)
  "Call THUNK with `nelisp-actor' struct accessors' `compiler-macro'
property suppressed, restoring it afterward even on a non-local exit.

Real Emacs cl-lib's `cl-defstruct' accessors carry a `compiler-macro'
property that `macroexpand-all' (and, transitively, `generator.el's
CPS transform, which has to macroexpand the WHOLE body to find every
`iter-yield', including ones buried inside macros like `nelisp-
receive') uses to inline each accessor down to `aref'/`aset' plus a
`cl-struct-NAME-tags' type check -- real Emacs's OWN struct
representation.  NeLisp's `cl-defstruct' polyfill
\(`scripts/nelisp-stdlib-prelude.el', Doc 50 stage 4e\) represents
structs completely differently -- `nelisp--record-ref'/`-set' on what
its own commentary calls \"a genuine tag-12 record\", not a plain
vector, and it does not define `cl-struct-NAME-tags' at all -- so
baking in real Emacs's inlined accessor bodies would bake in a
representation the standalone substrate cannot read (measured:
`void-variable: cl-struct-nelisp-actor-tags', running the FIRST
version of this script's generated output on `target/nelisp').
Suppressing the compiler-macro leaves accessor calls as plain function
calls, so each substrate's OWN `nelisp-actor-mailbox'/`nelisp-actor-
status' definition -- not one baked in from wherever this script
happened to run -- resolves them at run time, exactly as an ordinary
\(non-generated\) caller of this package already relies on."
  (let* ((accessors (nelisp-actor-cps-dump--struct-accessors 'nelisp-actor))
         (saved (mapcar (lambda (fn) (cons fn (function-get fn 'compiler-macro)))
                        accessors)))
    (unwind-protect
        (progn
          (dolist (fn accessors) (function-put fn 'compiler-macro nil))
          (funcall thunk))
      (dolist (pair saved) (function-put (car pair) 'compiler-macro (cdr pair))))))

(defconst nelisp-actor-cps-dump--setter-replacements
  '((nelisp-actor-status . nelisp-actor--set-status))
  "Alist of (ACCESSOR . REPLACEMENT-FN) for struct setters this script
rewrites post-expansion.  See `nelisp-actor-cps-dump--fix-setf-calls':
suppressing a `cl-defstruct' accessor's `compiler-macro' property (so
its GETTER stays a plain function call, portable across substrates)
leaves that accessor's SETTER -- `((setf ACCESSOR) VALUE PLACE)' --
calling a designator nothing actually defines on host Emacs
\(measured: `invalid-function (setf nelisp-actor-status)'\).
REPLACEMENT-FN takes (PLACE VALUE), matching `nelisp-actor--set-
status''s own (ACTOR VALUE) argument order, NOT `((setf ACCESSOR)
VALUE PLACE)''s VALUE-then-PLACE order -- `nelisp-actor-cps-dump--fix-
setf-calls' swaps them.  Only `nelisp-actor-status' is here because it
is the only struct setter `nelisp-receive'/`nelisp-yield''s macro
templates use today; add a row (and the matching `nelisp-actor--set-
FIELD' helper in nelisp-actor.el) if a future actor-thunk body needs
another one -- this script errors loudly instead of silently emitting
an uncallable form when it meets a setter with no row here.")

(defun nelisp-actor-cps-dump--setf-call-accessor (head)
  "Return the accessor symbol when HEAD is a `(setf ACCESSOR)' function
designator, else nil.

`macroexpand-all''s gv/setf expansion does NOT represent this
designator as the 2-element list `(setf ACCESSOR)' Common-Lisp-style
function-name syntax would suggest -- empirically, with the
accessor's `compiler-macro' suppressed, it is a single SYMBOL whose
`symbol-name' is literally the text \"(setf ACCESSOR)\", parens, space
and all (confirmed directly: `(symbol-name (car (macroexpand-all
'(setf (foo-bar x) 5)))))' => \"(setf foo-bar)\").  Parse that text
back into the accessor symbol rather than assuming a list shape a
first, list-based version of this script got wrong silently until
tested against `target/nelisp'."
  (and (symbolp head)
       (let ((name (symbol-name head)))
         (and (string-match "\\`(setf \\(.+\\))\\'" name)
              (intern (match-string 1 name))))))

(defun nelisp-actor-cps-dump--fix-setf-calls (form)
  "Rewrite every `((setf ACCESSOR) VALUE PLACE)' subform of FORM (see
`nelisp-actor-cps-dump--setter-replacements') into a plain call of its
replacement function, args reordered to (PLACE VALUE).  Signals if
FORM contains a `(setf ACCESSOR)' call-head this script has no
replacement for, rather than emitting a call nothing can resolve."
  (cond
   ((and (consp form) (nelisp-actor-cps-dump--setf-call-accessor (car form)))
    (let* ((accessor (nelisp-actor-cps-dump--setf-call-accessor (car form)))
           (replacement (cdr (assq accessor nelisp-actor-cps-dump--setter-replacements))))
      (unless replacement
        (error "nelisp-actor-cps-dump: no replacement registered for setter %S -- add a row to `nelisp-actor-cps-dump--setter-replacements'"
               accessor))
      (unless (= (length (cdr form)) 2)
        (error "nelisp-actor-cps-dump: unexpected arity for %S: %S" (car form) form))
      (list replacement
            (nelisp-actor-cps-dump--fix-setf-calls (nth 1 (cdr form)))
            (nelisp-actor-cps-dump--fix-setf-calls (nth 0 (cdr form))))))
   ((consp form)
    (cons (nelisp-actor-cps-dump--fix-setf-calls (car form))
          (nelisp-actor-cps-dump--fix-setf-calls (cdr form))))
   (t form)))

(defun nelisp-actor-cps-dump--substitute (form)
  "Return FORM with every `(nelisp-actor-lambda ...)' subform replaced
by its `macroexpand-all' expansion (with struct-accessor inlining
suppressed -- see `nelisp-actor-cps-dump--call-without-struct-
inlining').  `nelisp-actor-lambda' itself expands to `(iter-lambda ()
,@body)' (see nelisp-actor.el); expanding the WHOLE `nelisp-actor-
lambda' form rather than hand-unwrapping it first means this script
tracks whatever that macro does, including if it is ever changed,
rather than assuming its current one-line shape.  Recurses into the
rest of FORM unchanged -- everything outside a `nelisp-actor-lambda'
form (the enclosing `let'/`setq'/`nelisp-spawn'/`nelisp-actor-run-
until-idle' calls) is copied verbatim, so the generated function's
overall shape -- and, critically, which lexical variables its actor
thunks close over (e.g. a shared, mutated `trail' list both actors
`push' onto) -- stays identical to the source."
  (cond
   ((and (consp form) (eq (car form) 'nelisp-actor-lambda))
    (nelisp-actor-cps-dump--fix-setf-calls
     (nelisp-actor-cps-dump--call-without-struct-inlining
      (lambda () (macroexpand-all form)))))
   ((consp form)
    (cons (nelisp-actor-cps-dump--substitute (car form))
          (nelisp-actor-cps-dump--substitute (cdr form))))
   (t form)))

(defun nelisp-actor-cps-dump--read-defun (source-path name)
  "Read SOURCE-PATH and return its top-level `(defun NAME ...)' form."
  (with-temp-buffer
    (insert-file-contents source-path)
    (goto-char (point-min))
    (let ((found nil))
      (while (and (not found) (not (eobp)))
        (let ((start (point))
              (form (condition-case nil (read (current-buffer))
                      (end-of-file (goto-char (point-max)) nil))))
          (when (and (consp form) (eq (car form) 'defun) (eq (nth 1 form) name))
            (setq found form))
          (when (= (point) start) (goto-char (point-max)))))
      (unless found
        (error "nelisp-actor-cps-dump: `%s' not found in %s" name source-path))
      found)))

(defun nelisp-actor-cps-dump-write (source-path defun-name out-path new-name)
  "Transform DEFUN-NAME from SOURCE-PATH, renamed NEW-NAME, into OUT-PATH."
  (let* ((form (nelisp-actor-cps-dump--read-defun source-path defun-name))
         (transformed (nelisp-actor-cps-dump--substitute form))
         (renamed (append (list 'defun new-name) (cddr transformed))))
    (with-temp-file out-path
      (insert
       (format
        ";;; %s --- GENERATED: build-time CPS transform of the ping-pong demo -*- lexical-binding: t; -*-\n\n"
        (file-name-nondirectory out-path)))
      (insert ";; SPDX-License-Identifier: GPL-3.0-or-later\n\n")
      (insert ";;; Commentary:\n\n")
      (insert
       (format
        ";; GENERATED by `packages/nelisp-actor/scripts/nelisp-actor-cps-dump.el'
;; (run under Emacs %s) from `%s's `%s'.  Doc 193 §4.3/§4.4 Phase 1.
;;
;; Every `nelisp-actor-lambda' form has been replaced by its
;; `macroexpand-all' output under REAL `generator.el': ordinary
;; closures implementing the CPS state machine directly.  No
;; `iter-lambda'/`iter-yield' macro call remains anywhere in this
;; file -- `nelisp-spawn' just `funcall's whatever thunk it is given
;; and does not care how the resulting iterator was built, so these
;; plug into `nelisp-actor.el' exactly as the macro-built ones do, and
;; run on the standalone substrate via the `iter-next'/`iter-close'/
;; `iter-end-of-sequence' shim `nelisp-actor.el' installs when
;; `generator.el' is absent.
;;
;; DO NOT EDIT BY HAND.  Regenerate with `make nelisp-actor-cps-baseline'.\n\n"
        emacs-version (file-name-nondirectory source-path) defun-name))
      (insert ";;; Code:\n\n")
      (let ((print-length nil)
            (print-level nil)
            (print-circle nil))
        (pp renamed (current-buffer)))
      (insert (format "\n(provide '%s)\n" (file-name-base out-path)))
      (insert (format "\n;;; %s ends here\n" (file-name-nondirectory out-path))))))

(provide 'nelisp-actor-cps-dump)

;;; nelisp-actor-cps-dump.el ends here
