#!/usr/bin/env bash
# Source-command evaluator substrate artifact gate for Doc 154 Stage B.
#
# This gate uses the exact source-command substrate generated by
# scripts/nelisp-standalone-build.el, without the final command dispatch.  The
# default mode proves the substrate boundary is stable and cheap to inspect.
# --heavy additionally attempts eval-only .nelc materialization through
# target/nelisp, which currently exposes the Doc 154 Stage B compiler/reader
# bottleneck.
set -euo pipefail

# A gate whose only output is its own result lines cannot be told apart from a
# gate that ran nothing.  CASES counts the checks that finished; the trap
# reports it however the script exits, so a failure says how far it got.
# Findings comes from the exit status: this script stops at the first failure.
CASES=0
gate_report_count() {
  gate_rc=$?
  if [ "$gate_rc" -eq 0 ]; then
    printf 'GATE-COUNT checked=%s findings=0\n' "$CASES"
  else
    printf 'GATE-COUNT checked=%s findings=1\n' "$CASES"
  fi
}


REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

EMACS="${EMACS:-emacs}"
NELISP="${NELISP:-$REPO_ROOT/target/nelisp}"
BUILD=1
HEAVY=0
HEAVY_TIMEOUT_SECONDS="${NELISP_SUBSTRATE_HEAVY_TIMEOUT_SECONDS:-180}"
# Repo-local, not `mktemp -d' (which defaults to $TMPDIR/`/tmp'): the paths
# under TMP_DIR get embedded as literal Lisp strings in `--eval' below and
# handed to a SEPARATE Emacs process.  2026-08-23 Windows inventory: Git
# Bash's `mktemp -d' returned a `/tmp/...' path in the MSYS namespace;
# native Windows Emacs has no knowledge of that mount table and resolved
# the same literal text as `c:/tmp/...', which does not exist
# (`file-missing').  A path under the repo's own `target/' directory
# resolves identically from both sides -- there is no separate namespace
# to disagree about -- so this sidesteps the problem structurally rather
# than trying to translate one namespace into the other.
mkdir -p "$REPO_ROOT/target"
TMP_DIR="$(mktemp -d -p target)"

cleanup() {
  gate_report_count
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-build) BUILD=0; shift ;;
    --heavy) HEAVY=1; shift ;;
    --emacs) EMACS="$2"; shift 2 ;;
    --nelisp) NELISP="$2"; shift 2 ;;
    *)
      echo "usage: $0 [--no-build] [--heavy] [--emacs EMACS] [--nelisp PATH]" >&2
      exit 2
      ;;
  esac
done

# Needs a host that can run the configured target; ask the build script's
# own predicate rather than a bare `[ -x $NELISP ]' test, which cannot tell
# a built-but-foreign-architecture binary apart from a missing one.  Same
# convention as tools/selfhost-test.sh.  Non-heavy mode below never
# executes $NELISP (only host Emacs), so it does not need this gate; it is
# asked once up front and reused by both the `--heavy' early check and the
# default-mode profile_smoke step further down.
set +e
"$EMACS" --batch -Q -L lisp -L src -L scripts -l nelisp-standalone-build \
  --eval '(kill-emacs (if (nelisp-standalone--target-runnable-on-host-p) 0 3))' \
  >/dev/null 2>&1
target_runnable_rc=$?
set -e
TARGET_RUNNABLE=0
case "$target_runnable_rc" in
  0) TARGET_RUNNABLE=1 ;;
  3) TARGET_RUNNABLE=0 ;;
  *)
    echo "substrate_gate_fail reason=cannot-ask-host-runnability rc=$target_runnable_rc" >&2
    exit 1
    ;;
esac

if [ "$HEAVY" -eq 1 ] && [ "$TARGET_RUNNABLE" -eq 0 ]; then
  echo "GATE-SKIP target ${NELISP_STANDALONE_TARGET:-linux-x86_64} cannot run on host $(uname -s)/$(uname -m)"
  echo "substrate_gate_result label=source_command_substrate_gate rc=0 skipped=1"
  exit 0
fi

if [ "$BUILD" -eq 1 ]; then
  make standalone-reader
fi

if [ "$HEAVY" -eq 1 ] && [ ! -x "$NELISP" ]; then
  echo "substrate_gate_fail reason=missing-nelisp path=$NELISP" >&2
  exit 1
fi

if [ "$HEAVY" -eq 1 ] && ! command -v timeout >/dev/null 2>&1; then
  echo "substrate_gate_fail reason=missing-timeout-command" >&2
  exit 1
fi

FULL_SRC="$TMP_DIR/source-command-full.el"
SUBSTRATE_SRC="$TMP_DIR/source-command-substrate.el"
SUBSTRATE_ART="$SUBSTRATE_SRC.nelc"
PROFILE_SRC="$TMP_DIR/profile-smoke.el"
PROFILE_ART="$PROFILE_SRC.nelc"

run_timed() {
  local label="$1"; shift
  local out_file="$TMP_DIR/$label.out"
  local err_file="$TMP_DIR/$label.err"
  local start end rc
  start="$(date +%s%3N)"
  set +e
  "$@" >"$out_file" 2>"$err_file"
  rc=$?
  set -e
  end="$(date +%s%3N)"
  printf 'substrate_gate_result label=%s rc=%s ms=%s out=%s\n' \
    "$label" "$rc" "$((end - start))" \
    "$(tr '\n' ' ' <"$out_file" | sed 's/[[:space:]]*$//')"
  if [ "$rc" -ne 0 ]; then
    sed 's/^/substrate_gate_stderr /' "$err_file" >&2
    exit "$rc"
  fi
  CASES=$((CASES + 1))
}

expect_out() {
  local label="$1" expected="$2"
  local actual
  actual="$(cat "$TMP_DIR/$label.out")"
  if [ "$actual" != "$expected" ]; then
    printf 'substrate_gate_fail label=%s reason=output-mismatch expected=%s actual=%s\n' \
      "$label" "$expected" "$actual" >&2
    exit 1
  fi
}

run_timed dump_sources \
  "$EMACS" -Q --batch -L lisp -L src -L scripts \
  --eval "(progn (require 'nelisp-standalone-build) (with-temp-file \"$FULL_SRC\" (insert (nelisp-standalone--artifact-source-command-cache-src))) (with-temp-file \"$SUBSTRATE_SRC\" (insert (nelisp-standalone--artifact-source-command-substrate-src))))"

full_bytes="$(wc -c <"$FULL_SRC" | tr -d ' ')"
substrate_bytes="$(wc -c <"$SUBSTRATE_SRC" | tr -d ' ')"
full_sha="$(sha256sum "$FULL_SRC" | awk '{print $1}')"
substrate_sha="$(sha256sum "$SUBSTRATE_SRC" | awk '{print $1}')"
printf 'substrate_gate_metric full_bytes=%s substrate_bytes=%s full_sha256=%s substrate_sha256=%s\n' \
  "$full_bytes" "$substrate_bytes" "$full_sha" "$substrate_sha"

if grep -q '^(if (string= (car nelisp-standalone-argv)' "$SUBSTRATE_SRC"; then
  echo "substrate_gate_fail reason=substrate-source-still-has-command-dispatch" >&2
  exit 1
fi

if ! grep -q 'nelisp-standalone-source-cache-load-artifact' "$SUBSTRATE_SRC"; then
  echo "substrate_gate_fail reason=missing-source-cache-load-artifact-helper" >&2
  exit 1
fi

cat >"$PROFILE_SRC" <<'EOF'
(defun substrate-profile-smoke (x) x)
(provide 'substrate-profile-smoke)
EOF

# `-x' alone cannot tell "missing" apart from "built for a target this host
# cannot run" (2026-08-23 Windows inventory finding for the sibling gates
# above) -- $TARGET_RUNNABLE covers the second case.
if [ "$TARGET_RUNNABLE" -eq 1 ] && [ -x "$NELISP" ]; then
  run_timed profile_smoke \
    "$NELISP" compile-elisp-artifact --kind nelc --module-policy eval-only \
    --profile-stages --profile-forms --input "$PROFILE_SRC" --output "$PROFILE_ART"
  if ! grep -q '^artifact_profile stage=read-forms ' "$TMP_DIR/profile_smoke.err"; then
    echo "substrate_gate_fail reason=missing-profile-read-forms" >&2
    exit 1
  fi
  if ! grep -q '^artifact_profile_form ' "$TMP_DIR/profile_smoke.err"; then
    echo "substrate_gate_fail reason=missing-profile-form" >&2
    exit 1
  fi
  if ! grep -q '^artifact_profile stage=total ' "$TMP_DIR/profile_smoke.err"; then
    echo "substrate_gate_fail reason=missing-profile-total" >&2
    exit 1
  fi
elif [ "$TARGET_RUNNABLE" -eq 0 ]; then
  echo "substrate_gate_result label=profile_smoke rc=77 skipped=1 reason=target-unrunnable"
else
  echo "substrate_gate_result label=profile_smoke rc=77 skipped=1 reason=missing-nelisp"
fi

if [ "$HEAVY" -eq 1 ]; then
  run_timed compile_substrate_artifact_eval_only \
    timeout "$HEAVY_TIMEOUT_SECONDS" \
    "$NELISP" compile-elisp-artifact --kind nelc --module-policy eval-only \
    --input "$SUBSTRATE_SRC" --output "$SUBSTRATE_ART"

  if [ ! -f "$SUBSTRATE_ART" ] || [ ! -f "$SUBSTRATE_ART.manifest.el" ]; then
    echo "substrate_gate_fail reason=missing-substrate-artifact" >&2
    exit 1
  fi

  run_timed load_substrate_artifact \
    timeout "$HEAVY_TIMEOUT_SECONDS" \
    "$NELISP" eval-elisp-artifact "$SUBSTRATE_ART" \
    '(nelisp-standalone-source-cache--skip-ws "  x" 0)'
  expect_out load_substrate_artifact "2"

  if ! grep -q ':source' "$SUBSTRATE_ART.manifest.el"; then
    echo "substrate_gate_fail reason=manifest-missing-source-record" >&2
    exit 1
  fi
else
  echo "substrate_gate_result label=compile_substrate_artifact_eval_only rc=77 skipped=1 reason=heavy-opt-in"
fi

CASES=$((CASES + 1))
echo "substrate_gate_result label=source_command_substrate_gate rc=0"
